actividades/urls.py
from django.conf.urls import url
from actividades.views import *

urlpatterns = [

    url(r'^$', foro.as_view(), name='Forum'),
    url(r'^(?P<slug>[\w-]+)/insert_speech/$', insert_speech.as_view(), name='Insert_Speech'),
    url(r'^(?P<slug>[\w-]+)/$', foro_topic.as_view(), name='Forum_Topic'),
    url(r'^(?P<slug>[\w-]+)/(?P<slug1>[\w-]+)/$', foro_detail.as_view(), name='Forum_Detail'),
    url(r'^filter/type/(?P<slug>[\w-]+)/$', foro_types.as_view(), name='Forum_Types'),
    url(r'^(?P<speech_id>[0-9]+)/nuevo_recurso$', subirRecurso.as_view(), name='subir_recurso'),

    url(r'^create_profile/(?P<pk>[0-9]+)$', createProfile.as_view(), name='create_profile'),
    url(r'^edit_profile/(?P<pk>[0-9]+)$', ProfileUpdateView.as_view(), name='edit_profile'),
    url(r'^view_profile_forum/(?P<pk>[0-9]+)$', view_profile_forum.as_view(), name='View_Profile'),

]

becas/urls.py
from django.conf.urls import url
from becas.views import becas


urlpatterns = [
    url(r'^$', becas.as_view(), name='becas'),
]

camisetas/urls.py
from django.conf.urls import url, include
from camisetas.views import *

urlpatterns = [
    url(r'^camisetas_pendientes/$', camisetas_pendientes, name='camisetas_pendientes'),
    url(r'^delete_pedido/$', deletePedido, name='ajax_delete_pedido'),
    url(r'^agregar_pedido/$', agregar_pedido, name='ajax_agregar_pedido'),
    url(r'^pagar_pedido/(?P<pedido_id>[0-9]+)/$', pagarPedido, name='pagar_pedido'),
    url(r'^editar_pedido/$', editarPedido, name='editar_pedido'),
    url(r'^pagar_todos/$', pagarTodo, name='pagar_todo'),
    url(r'^carrito/$', Carrito.as_view(), name='carrito'),
    url(r'^(?P<style_id>[0-9]+)/encargar/$', createCamiseta.as_view(), name='encargar_camiseta'),
    url(r'^$', tshirt_list.as_view(), name='tshirt'),
    ]

faq/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from faq.views import Faq

urlpatterns = [
    url(r'^$', Faq.as_view(), name='faq'),
    ]

sitios/urls.py
from django.conf.urls import url, include
from web1.views import *
from web1.vistas.User import *
from django.conf.urls.static import static
from django.conf import settings
from web1.admin import admin_site
from web1.ajax import matricularse, deleteMatricularse, profileAddLike, deleteRecurso

extra_patterns = [

    url(r'^accounts/', include('registration.backends.hmac.urls')),
    url(r'^tshirts/', include('camisetas.urls', namespace='tshirts')),
    url(r'^faq/', include('faq.urls', namespace='faq')),
    url(r'^activity/', include('actividades.urls', namespace='activity')),
    url(r'^becas/', include('becas.urls', namespace='becas')),
    ]


user_patterns = [

    url(r'^accounts/view_profile/(?P<pk>[\w-]+)/$', view_profile_admin.as_view(), name='View_Profile_Admin'),
    url(r'^accounts/new_user/$', createUser.as_view(), name='New_User'),
    url(r'^accounts/new_profile/$', createProfile.as_view(), name='New_Profile'),
    url(r'^accounts/logout/$', salir, name='salir'),
    url(r'^accounts/edit_profile/(?P<pk>[0-9]+)$', ProfileUpdateView.as_view(), name='edit_profile'),
    url(r'^accounts/create_event/(?P<pk>[0-9]+)$', createEvent.as_view(), name='Create_Event'),
    url(r'^accounts/login/$', entrar, name='entrar'),

]
ajax_patterns = [
        # Esto es lo de matricularse ------------
    url(r'^ajax/enroll/', matricularse, name='ajax_matricula'),
    url(r'^ajax/delete_enroll/', deleteMatricularse, name='ajax_delete_matricula'),
    # Esto es lo de dar like -------------------------
    url(r'^ajax/add_like/$', profileAddLike, name='add_like'),
    url(r'^ajax/delete_recurso/', deleteRecurso, name='ajax_delete_recurso'),
]


urlpatterns = user_patterns + extra_patterns + ajax_patterns + [

    url(r'^admin/', admin_site.urls),
    url(r'^$', index, name='index'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/sitios_web/base.html
{% load static %}
<!DOCTYPE html>
{% load i18n %}
<html lang="en">
<head>
    <title>ECSL</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'paginas/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'paginas/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'paginas/css/jquery-ui.css' %}">
    <script src="{% static 'paginas/js/jquery.min.js' %}"></script>
    <script src="{% static 'paginas/js/jquery-ui.js' %}"></script>
    <script src="{% static 'paginas/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'paginas/js/DjangoAjax.js' %}"></script>
    <script src="{% static 'paginas/js/min-height.js' %}"></script>

</head>
<body>
<header>
    {% block head %}


        <nav class="navbar navbar-default nav-main navbar-fixed-top" role="navigation">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse"
                            data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li {% ifequal url "/" %}class="active"{% endifequal %}><a
                                href="{% url 'index' %}">{% trans "Inicio" %}</a></li>
                        <li {% ifequal url "/activity/" %}class="active"{% endifequal %}><a
                                href="{% url 'activity:Forum' %}">{% trans "Actividades" %}</a></li>
                        {#           <li {% ifequal url "/calender/" %}class="active"{% endifequal %}><a#}
                        {#                                href="{% url 'Agenda' %}">{% trans "Agenda" %}</a></li>#}
                        <li {% ifequal url "/tshirts/" %}class="active"{% endifequal %}><a
                                href="{% url 'tshirts:tshirt' %}">{% trans "Camisetas" %}</a></li>
                        <li {% ifequal url "/becas/" %}class="active"{% endifequal %}><a
                                href="{% url 'becas:becas' %}">{% trans "Becas" %}</a></li>
                        <li {% ifequal url "/faq/" %}class="active"{% endifequal %}><a
                                href="{% url 'faq:faq' %}">{% trans "FAQ" %}</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    {% trans " Perfilde " %}{{ user.username }}
                                    <span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    {% if user.forum_user_profile %}
                                    <li><a href="{% url 'activity:View_Profile' user.forum_user_profile.pk %}">{% trans "Ver Perfil" %}</a>
                                    </li>
                                    <li><a href="{% url 'activity:edit_profile' user.forum_user_profile.pk %}">{% trans "Editar" %}</a></li>

                                    {% else %}
                                    <li><a href="{% url 'auth_password_change' %}">{% trans "Cambiar Contraseña" %}</a>
                                    <li><a href="{% url 'activity:create_profile' user.pk %}">{% trans "Crear Perfil" %}</a>
                                    </li>
                                    {% endif %}
                                </ul>
                            </li>
                            <li><a href="{% url 'auth_logout' %}" title="Log Out"><i class="fa fa-power-off"></i></a></li>
                        {% else %}

                            <li {% ifequal url "/accounts/new_user/" %}class="active"{% endifequal %}>
                            <a href="{% url 'New_User' %}" class="btn btn-lg btn-register">Register</a>
                            </li>
                            <li {% ifequal url "/accounts/login/" %}class="active"{% endifequal %}><a
                                    href="{% url 'auth_login' %}">{% trans "Entrar " %}</a></li>

                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>


    {% endblock %}
</header>
{% block banner %}
{% endblock %}
<div class="container {% ifnotequal url "/" %}main-container{% endifnotequal %}">
    <div class="row">
        <div class="col-sm-12">
            {% block messages %}
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}"><i
                                class="fa fa-{% if message.tags == 'success' %}check{% elif message.tags == 'warning' %}exclamation{% elif message.tags == 'danger' %}minus{% else %}{{ message.tags }}{% endif %}-circle"></i>
                            <button type="button" class="close" data-dismiss="alert"><span
                                    aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endblock %}

            {% block content %}
            {% endblock %}
            {% include 'camisetas/carrito_widget.html' %}
        </div>
    </div>
</div>
{% block fluid %}
{% endblock %}
{% block footer %}
    <footer class="footer {% ifequal url "/" %}footer-home{% endifequal %}">
        <div class="footer-container">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="footer-left">

                        </div>
                        <div class="footer-center">

                        </div>
                        <div class="footer-right pull-right">
                            <h2 class="text-uppercase">
                                Síguenos
                            </h2>
                            <ul class="links">
                                <li>
                                    <a><span class="fa fa-2x fa-facebook-square"></span></a>
                                </li>
                                <li>
                                    <a><span class="fa fa-2x fa-twitter-square"></span></a>
                                </li>
                                <li>
                                    <a><span class="fa fa-2x fa-linkedin-square"></span></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-nav text-center">
            <p>Alajuela, Costa Rica, 20-21 de julio de 2017</p>
        </div>
    </footer>
{% endblock %}
{% block script %}
{% endblock %}
<script src="{% static 'paginas/js/cart.js' %}"></script>
<script>
    jQuery(document).ready(function ($) {
        {% for item in pedidos %}
            var datacart = {
                'amount':{{item.amount}},
                'talla': '{{item.size}}',
                'idshirt':{{item.pk}},
                'price':{{item.style.price}},
                'name': '{{item.style.name}}'
            };
            addToCart(datacart, {{ item.pk }});
        {% endfor %}
    })
</script>

templates/sitios_web/home_sites.html
{% extends 'sitios_web/base.html' %}

{% load i18n %}
{% load static %}

{% block banner %}
    <div class="banner-ecsl">
        {% for object in sitios %}
            <div class="image-background"
                 style="background-size: 100%; background: url(media/{{ object.banner }});     background-size: 100%;
                         background-position: 0 -15px;"></div>
            <div class="banner-opacity"></div>
            <div class="logo-img">
                <img src="media/{{ object.WebLogo }}" class="img-responsive">
                <div class="promo">
                    <h1>
                        {% trans object.slogan %}
                    </h1>
                </div>
            </div>
        {% endfor %}

    </div>
{% endblock %}

{% block content %}
    <div class="block-encuentro text-center">
        <h1 class="title">Encuentro</h1>
        <h2 class="title-2 letter-spacing-3">Centroamericano</h2>
        <h2 class="title-2 letter-spacing-2">de Software Libre</h2>
        <h2 class="title-anho"><span>2017</span></h2>
        <h2 class="title-2">Alajuela, Costa Rica</h2>
    </div>
{% endblock %}

{% block fluid %}
    <div class="block-actividades">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <h1 class="title">Propuestas de Actividades</h1>
                    {% for type in types %}

                        <div class="col-sm-4">
                            <img src="{{ type.icons }}" class="img-responsive pull-left">
                            <a href="{% url 'activity:Forum_Types' type.slug %}"><h2>{{ type.name }}</h2></a>
                        </div>

                    {% endfor %}

                </div>
            </div>
        </div>
    </div>

    <div class="block-patrocinadores">
        <div class="container">
            <h1 class="text-center text-uppercase patrocinadores-title">
                <span>Patrocinadores</span>
            </h1>
            <div class="row patrocinadores">
                {% for foo in imagen %}
                    {% if forloop.counter <= 4 %}
                        <a href="{{ foo.web }}" target="_blank"
                           class="col-sm-4 col-md-3 patrocinador-item text-center">
                            <div class="patrocinador-img">
                                <img src="{{ foo.logo.url }}" class="img-responsive" title="{{ foo.name }}">
                            </div>
                        </a>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}