camisetas/urls.py
from django.conf.urls import url, include
from camisetas.views import *

urlpatterns = [
    url(r'^camisetas_pendientes/$', camisetas_pendientes, name='camisetas_pendientes'),
    url(r'^delete_pedido/$', deletePedido, name='ajax_delete_pedido'),
    url(r'^agregar_pedido/$', agregar_pedido, name='ajax_agregar_pedido'),
    url(r'^pagar_pedido/(?P<pedido_id>[0-9]+)/$', pagarPedido, name='pagar_pedido'),
    url(r'^editar_pedido/$', editarPedido, name='editar_pedido'),
    url(r'^pagar_todos/$', pagarTodo, name='pagar_todo'),
    url(r'^carrito/$', Carrito.as_view(), name='carrito'),
    url(r'^(?P<style_id>[0-9]+)/encargar/$', createCamiseta.as_view(), name='encargar_camiseta'),
    url(r'^$', tshirt_list.as_view(), name='tshirt'),
    ]

faq/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from faq.views import Faq

urlpatterns = [
    url(r'^$', Faq.as_view(), name='faq'),
    ]

sitios/urls.py
from django.conf.urls import url, include
from web1.views import *
from web1.vistas.User import *
from django.conf.urls.static import static
from django.conf import settings
from web1.admin import admin_site
from web1.ajax import matricularse, deleteMatricularse, profileAddLike, deleteRecurso

extra_patterns = [

    url(r'^accounts/', include('registration.backends.hmac.urls')),
    url(r'^tshirts/', include('camisetas.urls', namespace='tshirts')),
    url(r'^faq/', include('faq.urls', namespace='faq')),
    url(r'^activity/', include('actividades.urls', namespace='activity')),
    url(r'^becas/', include('becas.urls', namespace='becas')),
    ]


user_patterns = [

    url(r'^accounts/view_profile/(?P<pk>[\w-]+)/$', view_profile_admin.as_view(), name='View_Profile_Admin'),
    url(r'^accounts/new_user/$', createUser.as_view(), name='New_User'),
    url(r'^accounts/new_profile/$', createProfile.as_view(), name='New_Profile'),
    url(r'^accounts/logout/$', salir, name='salir'),
    url(r'^accounts/edit_profile/(?P<pk>[0-9]+)$', ProfileUpdateView.as_view(), name='edit_profile'),
    url(r'^accounts/create_event/(?P<pk>[0-9]+)$', createEvent.as_view(), name='Create_Event'),
    url(r'^accounts/login/$', entrar, name='entrar'),

]
ajax_patterns = [
        # Esto es lo de matricularse ------------
    url(r'^ajax/enroll/', matricularse, name='ajax_matricula'),
    url(r'^ajax/delete_enroll/', deleteMatricularse, name='ajax_delete_matricula'),
    # Esto es lo de dar like -------------------------
    url(r'^ajax/add_like/$', profileAddLike, name='add_like'),
    url(r'^ajax/delete_recurso/', deleteRecurso, name='ajax_delete_recurso'),
]


urlpatterns = user_patterns + extra_patterns + ajax_patterns + [

    url(r'^admin/', admin_site.urls),
    url(r'^$', index, name='index'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

camisetas/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db.models import *
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from web1.models import Eventos
from django.contrib.sites.models import Site


class TshirtStyle(Model):
    gender_choice = (
        ('M', 'Masculino'),
        ('F', 'Femenino')

    )

    description = TextField(verbose_name=_('Descripción'))
    gender = CharField(max_length=1, choices=gender_choice, verbose_name=_('Género'))
    img1 = ImageField(verbose_name=_('Imagen 1'), upload_to='Tshirt/')
    img2 = ImageField(verbose_name=_('Imagen 2'), upload_to='Tshirt/')
    img3 = ImageField(verbose_name=_('Imagen 3'), upload_to='Tshirt/')

    name = CharField(max_length=45, verbose_name=_('Nombre'))
    price = DecimalField(verbose_name=_('Precio'), decimal_places=2, max_digits=6)
    sites = ForeignKey(Site, on_delete=CASCADE, verbose_name=_('Sitios'))

    def __str__(self):
        return self.name


class Tshirt(Model):
    style = ForeignKey(TshirtStyle, on_delete=CASCADE, verbose_name=_('Estilo'))
    user = ForeignKey(User, on_delete=CASCADE, verbose_name=_('Usuario'))
    amount = PositiveIntegerField(verbose_name=_('Cantidad'))
    last_update = DateField(verbose_name=_('Última Actualización'))
    size = CharField(max_length=15, verbose_name=_('Talla'))
    pagada = BooleanField(default=False)

    def __str__(self):
        return self.style.name + ' ' + self.style.description

camisetas/forms.py
# -*- coding: utf-8 -*-
from camisetas.models import *
from django import forms


class TshirtForm(forms.ModelForm):
    class Meta:
        model = Tshirt
        fields = ['size', 'amount']

camisetas/views.py
from django.shortcuts import render, reverse, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.generic import *
from camisetas.models import *
from django.utils.decorators import method_decorator
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse, HttpResponseBadRequest
from camisetas.forms import TshirtForm
from django.utils.timezone import now
from django.contrib.sites.shortcuts import get_current_site
from django.http import Http404


@method_decorator(login_required, name='dispatch')
class tshirt_list(ListView):
    template_name = 'camisetas/Tshirt.html'
    context_object_name = 'camisetas'

    def get_context_data(self, **kwargs):
        context = super(tshirt_list, self).get_context_data(**kwargs)
        context['form'] = TshirtForm
        return context

    def get_queryset(self):
        return TshirtStyle.objects.filter(sites=get_current_site(self.request))

    def get(self, request, *arg, **kwargs):
        if get_current_site(request).domain == 'localhost:8000':
            raise Http404
        return super(tshirt_list, self).get(request, *arg, **kwargs)

class createCamiseta(CreateView, LoginRequiredMixin):
    template_name = 'camisetas/crear_camiseta.html'
    model = Tshirt
    fields = ['size', 'amount', ]
    success_url = '/tshirt'

    def form_valid(self, form):
        form.instance.style_id = self.kwargs['style_id']
        form.instance.user = self.request.user
        form.instance.last_update = now()
        return super(createCamiseta, self).form_valid(form)

    def get(self, request, *arg, **kwargs):
        if get_current_site(request).domain == 'localhost:8000':
            raise Http404
        return super(createCamiseta, self).get(request, *arg, **kwargs)

class Carrito(ListView, LoginRequiredMixin):
    template_name = 'camisetas/carrito.html'
    context_object_name = 'camisetas'

    def get_queryset(self):
        return Tshirt.objects.filter(pagada=False, style__sites=get_current_site(self.request))

    def get(self, request, *arg, **kwargs):
        if get_current_site(request).domain == 'localhost:8000':
            raise Http404
        return super(Carrito, self).get(request, *arg, **kwargs)


# pagar un solo pedido
@login_required()
def pagarPedido(request, pedido_id):
    tshirt = Tshirt.objects.get(pk=pedido_id, style__sites=get_current_site(request))
    # Aqui debe ir la funcion qu permite pagar por PayPal
    tshirt.pagada = True
    tshirt.save()
    messages.add_message(request, messages.SUCCESS, 'Gracias por comprar las camisetas del evento')
    return redirect('tshirts:carrito')


@login_required()
def editarPedido(request):
    id_pedido = request.POST['id_pedido']
    elemento = Tshirt.objects.get(pk=id_pedido, style__sites=get_current_site(request))
    elemento.amount = request.POST['amount']
    elemento.save()
    return JsonResponse({'mensaje': "Pedido eliminado"})

# pagar todos los pedidos del usuario autenticado
@login_required()
def pagarTodo(request):
    camisetas = Tshirt.objects.filter(user=request.user, style__sites=get_current_site(request))
    # Aqui debe ir la funcion qu permite pagar por PayPal
    for tshirt in camisetas:
        tshirt.pagada = True
        tshirt.save()
    messages.add_message(request, messages.SUCCESS, 'Gracias por comprar las camisetas del evento')
    return redirect('tshirts:tshirt')


@login_required()
def deletePedido(request):
    user = request.user
    id_pedido = request.POST['id_pedido']
    camiseta = get_object_or_404(Tshirt, pk=id_pedido)
    if user != camiseta.user:
        return HttpResponseBadRequest()
    else:
        camiseta.delete()
    return JsonResponse({'mensaje': "Pedido eliminado"})


@login_required()
def agregar_pedido(request):
    user = request.user
    amount = request.POST['amount']
    talla = request.POST['talla']

    id_sty = request.POST['id_style']

    obj = TshirtStyle.objects.get(pk=id_sty, sites=get_current_site(request))
    Tshirt.objects.create(user=user, style=obj, amount=amount, last_update=now(), size=talla)
    return JsonResponse({'id_camiseta': Tshirt.objects.last().pk})


# para poder saber las camisetas sin pagar mediante ajax pa los fronten cuando eliminen un pedido
# por ajax actualicen el indice de camisetas pendientes en el base
@login_required()
def camisetas_pendientes(request):
    user = request.user
    pendientes = user.profile.camisetas_sin_pagar
    return JsonResponse({'camisetas_pendientes': pendientes})

camisetas/templates/camisetas/Tshirt.html
{% extends "sitios_web/base.html" %}
{% load i18n %}
{% load static %}
{% load bootstrap3 %}

{% block content %}

    <h1 class="page-header">
        Camisetas
    </h1>

    <div class="row">


    <div class="modal fade" id="modalCart" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Pedidos</h4>
        </div>
        <div class="modal-body">
               {% csrf_token %}
        {% bootstrap_form form%}
        </div>
        <div class="modal-footer">
          <a class="btn btn-success cd-add-to-cart">Encargar</a>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
        {% for foo in camisetas %}
            <div class="col-sm-4">
                <div class="product-item">
                    <div class="make3D">
                        <div class="product-front">
                            <div class="shadow"></div>
                            <img src="{{ foo.img1.url }}" class="img-responsive">
                            <div class="image_overlay"></div>
                            <div class="view_gallery">Ver más</div>
                            <a data-toggle="modal" href="#modalCart" class="add_to_cart" data-idcart="{{ foo.pk }}" data-price="{{ foo.price }}" data-shirtname="{{ foo.name }}">Encargar</a>
                            <div class="stats">
                                <div class="stats-container">
                                    <span class="product_price">${{ foo.price }}</span>
                                    <span class="product_name">{{ foo.name }}</span>
                                </div>
                            </div>
                        </div>
                        <div class="product-back">
                            <div class="shadow"></div>

                            <div id="carousel-{{ forloop.counter }}" class="carousel slide" data-ride="carousel">
                                <!-- Wrapper for slides -->
                                <div class="carousel-inner">
                                    <div class="item active">
                                        <img src="{{ foo.img1.url }}" class="img-responsive">
                                    </div>
                                    <div class="item">
                                        <img src="{{ foo.img2.url }}" class="img-responsive">
                                    </div>
                                    <div class="item">
                                        <img src="{{ foo.img3.url }}" class="img-responsive">
                                    </div>
                                </div>

                                <!-- Controls -->
                                <a class="carouselPrev visible carousel-control" href="#carousel-{{ forloop.counter }}" role="button"
                                   data-slide="prev">
                                    <div class="y"></div>
                                    <div class="x"></div>
                                </a>
                                <a class="carouselNext visible carousel-control" href="#carousel-{{ forloop.counter }}" role="button"
                                   data-slide="next">
                                    <div class="y"></div>
                                    <div class="x"></div>
                                </a>
                            </div>
                            <div class="flip-back">
                            <div class="cy s1 s2 s3"></div>
                            <div class="cx s1 s2 s3"></div>
                        </div>
                        </div>

                    </div>

                </div>

            </div>

        {% endfor %}

        {% if not camisetas %}
            <div class="col-sm-12">
                <h3 class="text-warning">No quedan camisetas</h3>
            </div>
        {% endif %}
    </div>
{% endblock %}
{% block script %}
    <script src="{% static 'paginas/js/tshirt.js' %}"></script>
{% endblock %}

camisetas/templates/camisetas/carrito.html
{% extends "sitios_web/base.html" %}
{% load i18n %}
{% load static %}
{% block content %}

    <h1 class="page-header">
        Encargos
    </h1>

    {% for encargo in camisetas %}
        <h2> Estilo:{{ encargo.style.name }}</h2>
        <h3>Talla: {{ encargo.size}}</h3>
        <h3>Cantidad: {{ encargo.amount }}</h3>
        <a class="btn btn-success" href="{% url 'tshirts:pagar_pedido' encargo.pk %}">Pagar</a>
        <a class="btn btn-info" href="{% url 'tshirts:editar_pedido' encargo.pk %}">Editar</a>
        <a class="btn btn-danger" href="#" onclick="eliminarPedido({{encargo.pk}})">Eliminar</a>
    {% empty %}
    <h3>No tiene ningun encargo</h3>
    {% endfor %}

    <br>
    <br>
    <br>
    {% if camisetas %}
        <a class="btn btn-success" href="{% url 'tshirts:pagar_todo' %}"> Pagar Todo</a>
    {% endif %}

{% endblock %}
{% block script %}
    <script src="{% static 'paginas/js/tshirt.js' %}"></script>
    <script type="text/javascript">
    function eliminarPedido(id_pedido) {
            $.ajax({
                url: '/tshirts/delete_pedido/',
                type: "POST",
                data: {'id_pedido': id_pedido},
                success: function (response) {
                    $(document).reload;
                    //Esto les toca a los frontend ver que van a hacer cuando se elimine el pedido Arreglar
                }
            });
        }
    </script>

{% endblock %}

camisetas/templates/camisetas/carrito_widget.html
<div class="cd-cart-container empty">
                <a href="#0" class="cd-cart-trigger">
                    Compra
                    <ul class="count"> <!-- cart items count -->
                        <li>0</li>
                        <li>0</li>
                    </ul> <!-- .count -->
                </a>

                <div class="cd-cart">
                    <div class="wrapper">
                        <header>
                            <h2>Compra</h2>
                        </header>

                        <div class="body">
                            <ul>
                                <!-- products added to the cart will be inserted here using JavaScript -->
                            </ul>
                        </div>

                        <footer>
                            <a href="{% url 'tshirts:pagar_todo' %}" class="checkout"><em>Comprar - $<span>0</span></em></a>
                        </footer>
                    </div>
                </div> <!-- .cd-cart -->
            </div>

camisetas/templates/camisetas/crear_camiseta.html
{% extends 'base.html' %}
{% load i18n %}
{% load bootstrap3 %}
{% block content %}
    <h1>{% trans "Pedido" %}</h1>
    <div class="container">
        <form method="post">
            {% csrf_token %}
        {% bootstrap_form form%}
            <button class="btn btn-primary" type="submit">{% trans "Agregar al carrito" %}</button>
        </form>
    </div>
{% endblock %}

camisetas/templates/camisetas/editar_camiseta.html
{% extends 'base.html' %}
{% load i18n %}
{% load bootstrap3 %}
{% block content %}
    <h1>{% trans "Pedido" %}</h1>
    <div class="container">
        <form method="post">
            {% csrf_token %}
        {% bootstrap_form form%}
            <button class="btn btn-primary" type="submit">{% trans "Modificar" %}</button>
        </form>
    </div>
{% endblock %}