actividades/urls.py
from django.conf.urls import url
from actividades.views import *

urlpatterns = [

    url(r'^$', foro.as_view(), name='Forum'),
    url(r'^(?P<slug>[\w-]+)/insert_speech/$', insert_speech.as_view(), name='Insert_Speech'),
    url(r'^(?P<slug>[\w-]+)/$', foro_topic.as_view(), name='Forum_Topic'),
    url(r'^(?P<slug>[\w-]+)/(?P<slug1>[\w-]+)/$', foro_detail.as_view(), name='Forum_Detail'),
    url(r'^filter/type/(?P<slug>[\w-]+)/$', foro_types.as_view(), name='Forum_Types'),
    url(r'^(?P<speech_id>[0-9]+)/nuevo_recurso$', subirRecurso.as_view(), name='subir_recurso'),

    url(r'^create_profile/(?P<pk>[0-9]+)$', createProfile.as_view(), name='create_profile'),
    url(r'^edit_profile/(?P<pk>[0-9]+)$', ProfileUpdateView.as_view(), name='edit_profile'),
    url(r'^view_profile_forum/(?P<pk>[0-9]+)$', view_profile_forum.as_view(), name='View_Profile'),

]

faq/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from faq.views import Faq

urlpatterns = [
    url(r'^$', Faq.as_view(), name='faq'),
    ]

sitios/urls.py
from django.conf.urls import url, include
from web1.views import *
from web1.vistas.User import *
from django.conf.urls.static import static
from django.conf import settings
from web1.admin import admin_site
from web1.ajax import matricularse, deleteMatricularse, profileAddLike, deleteRecurso

extra_patterns = [

    url(r'^accounts/', include('registration.backends.hmac.urls')),
    url(r'^tshirts/', include('camisetas.urls', namespace='tshirts')),
    url(r'^faq/', include('faq.urls', namespace='faq')),
    url(r'^activity/', include('actividades.urls', namespace='activity')),
    url(r'^becas/', include('becas.urls', namespace='becas')),
    ]


user_patterns = [

    url(r'^accounts/view_profile/(?P<pk>[\w-]+)/$', view_profile_admin.as_view(), name='View_Profile_Admin'),
    url(r'^accounts/new_user/$', createUser.as_view(), name='New_User'),
    url(r'^accounts/new_profile/$', createProfile.as_view(), name='New_Profile'),
    url(r'^accounts/logout/$', salir, name='salir'),
    url(r'^accounts/edit_profile/(?P<pk>[0-9]+)$', ProfileUpdateView.as_view(), name='edit_profile'),
    url(r'^accounts/create_event/(?P<pk>[0-9]+)$', createEvent.as_view(), name='Create_Event'),
    url(r'^accounts/login/$', entrar, name='entrar'),

]
ajax_patterns = [
        # Esto es lo de matricularse ------------
    url(r'^ajax/enroll/', matricularse, name='ajax_matricula'),
    url(r'^ajax/delete_enroll/', deleteMatricularse, name='ajax_delete_matricula'),
    # Esto es lo de dar like -------------------------
    url(r'^ajax/add_like/$', profileAddLike, name='add_like'),
    url(r'^ajax/delete_recurso/', deleteRecurso, name='ajax_delete_recurso'),
]


urlpatterns = user_patterns + extra_patterns + ajax_patterns + [

    url(r'^admin/', admin_site.urls),
    url(r'^$', index, name='index'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

actividades/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django.db.models import *
from django.utils.translation import ugettext_lazy as _
from django.utils.timezone import now
from django.conf import settings
from django.utils.text import slugify
from django.contrib.sites.models import Site


class SpeechType(Model):
    speech_choice = (
        ('Talleres', 'Talleres'),
        ('Charlas', 'Charlas'),
        ('Diálogos', 'Diálogos')
    )

    speech_icons = (
        (settings.STATIC_URL + 'paginas/img/talleres.png', 'Talleres'),
        (settings.STATIC_URL + 'paginas/img/charlas.png', 'Charlas'),
        (settings.STATIC_URL + 'paginas/img/dialogos.png', 'Diálogos')
    )
    user = ForeignKey(User, on_delete=CASCADE, related_name='speechs_type_user', verbose_name=_('Usuario'))
    name = CharField(max_length=45, verbose_name=_('Nombre'), choices=speech_choice)
    icons = CharField(max_length=45, verbose_name=_('Iconos'), choices=speech_icons)
    slug = SlugField(unique=True, help_text='Generador de url, se recomienda no modificar')
    sites = ForeignKey(Site, on_delete=CASCADE, verbose_name=_('Sitios'))

    def __str__(self):
        return self.name


class Topic(Model):

    user = ForeignKey(User, on_delete=CASCADE, related_name='topic_user', verbose_name=_('Usuario'))
    name = CharField(max_length=45, verbose_name=_('Nombre'))
    description = TextField(verbose_name=_('Descripción'))
    slug = SlugField(unique=True, help_text='Generador de url, se recomienda no modificar')
    date_created = DateTimeField(verbose_name=_('Fecha de Creado'), auto_now_add=True)
    sites = ForeignKey(Site, on_delete=CASCADE, related_name='topic_user', verbose_name=_('Sitios'))

    class Meta:
        ordering = ["-date_created"]

    def __str__(self):
        return self.slug


class Speech(Model):

    class Meta:
        ordering = ["date_created"]

    speech_audience = (
        ('PG', 'Público General'),
        ('NB', 'Nivel Basico'),
        ('NI', 'Nivel Intermedio'),
        ('NA', 'Nivel Avanzado'),
        ('PRO', 'Profesional'),
    )

    speech_type = ForeignKey(SpeechType, verbose_name=_('Tipo de Actividad'))
    topic = ForeignKey(Topic, verbose_name=_('Tema'))
    user = ForeignKey(User, on_delete=CASCADE, related_name='speechs_user', verbose_name=_('Usuario'))
    audience = CharField(verbose_name=_('Público'), choices=speech_audience, max_length=45)
    description = TextField(verbose_name=_('Descripción'))
    notes = TextField(verbose_name=_('Notas'))
    skill_level = PositiveIntegerField(verbose_name=_('Nivel de Habilidad'))
    speaker_information = TextField(verbose_name=_('Información del Autor'))
    title = CharField(max_length=250, verbose_name=_('Título'))
    places = CharField(max_length=250, verbose_name=_('Lugares'), null=True)
    activity_start = DateTimeField(verbose_name=_('Fecha del Evento'), null=True)
    slug = SlugField(unique=True, help_text='Generador de url, se recomienda no modificar', max_length=255)
    date_created = DateTimeField(verbose_name=_('Fecha de Creado'), auto_now_add=True)
    published = BooleanField(verbose_name=_('¿Publicado?'), default=False)
    sites = ForeignKey(Site, on_delete=CASCADE, verbose_name=_('Sitios'))

    def __str__(self):
        return self.speech_type.name + ' de ' + self.topic.name

    def cantidad_de_likes(self):
        likes = self.profile_speech_likes.all()
        return likes.count()


class SpeechResource(Model):
    user = ForeignKey(User, on_delete=CASCADE, related_name='speechs_resource_user', verbose_name=_('Usuario'))
    speech = ForeignKey(Speech, related_name='recursos')
    recurso = FileField(upload_to='recursos/')
    sites = ForeignKey(Site, on_delete=CASCADE, verbose_name=_('Sitios'))

    def nombre(self):
        direccion = self.recurso.name
        nombre = direccion.split('/').pop()
        return nombre

    def get_absolute_url(self):
        return '/activity/' + self.speech.topic.slug + "/" + self.speech.slug


class Forum_User_Profile(Model):

    gender_choice = (
        ('Masculino', 'Masculino'),
        ('Femenino', 'Femenino')
    )

    user = OneToOneField(User, on_delete=models.CASCADE, verbose_name=_('Usuario'))
    name = CharField(max_length=255, verbose_name=_('Nombre'), blank=True)
    last_name = CharField(max_length=255, verbose_name=_('Apellido'), blank=True)
    institution = CharField(max_length=12, verbose_name=_('Institución'), blank=True)
    alimentary_restriction = TextField(verbose_name=_('Restrinción Alimentaria'), null=True)
    born_date = DateField(verbose_name=_('Fecha de Nacimiento'), null=True)
    gender = CharField(max_length=9, choices=gender_choice, verbose_name=_('Genero'), blank=True)
    health_consideration = TextField(verbose_name=_('Condiciones de Salud'), null=True)
    identification = CharField(max_length=12, verbose_name=_('Identificación'), null=True)
    nationality = CharField(max_length=12, verbose_name=_('Nacionalidad'), blank=True)
    snore = BooleanField(verbose_name=_('¿Ronca?'), default=False, blank=True)
    enrolled = BooleanField(verbose_name=_('¿Matriculado?'), default=False, blank=True)
    sites = ForeignKey(Site, on_delete=CASCADE, verbose_name=_('Sitios'))

    # About the likes and the register in the differents activities
    likes = ManyToManyField(Speech, related_name='profile_speech_likes', blank=True)
    matriculatedspeechs = ManyToManyField(Speech, blank=True)
    entry_country = IntegerField(verbose_name=_('Entradas del País'), null=True)
    out_country = IntegerField(verbose_name=_('Salidas del País'), null=True)
    entry_port = CharField(max_length=100, verbose_name=_('Puerto de Entrada'), null=True)
    out_port = CharField(max_length=100, verbose_name=_('Puerto de Salida'), null=True)
    entry_country_date = DateField(verbose_name=_('Fecha de Entrada al país'), null=True)
    out_country_date = DateField(verbose_name=_('Fecha de Salida del país'), null=True)
    letter = TextField(verbose_name=_('Carta Migratoria'), null=True)
    invitation_file = BooleanField(verbose_name=_('¿Email de Invitación?'), default=False)
    diploma = BooleanField(verbose_name=_('¿Email de Diploma?'), default=False)

actividades/forms.py
from registration.forms import *
from actividades.models import *
from web1.models import Profile, Eventos


class InsertTopic(forms.ModelForm):

    class Meta:
        model = Topic
        fields = ['name', 'description']


class ProfileForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ['name', 'LastName', 'country','gender', 'identification',]


class EventoForm(forms.ModelForm):

    class Meta:
        model = Eventos
        fields = ['event_name', 'date_start', 'date_end','country', 'places',]


class InsertSpeech(forms.ModelForm):

    class Meta:
        model = Speech
        fields = ['title', 'description', 'notes', 'speaker_information','audience', 'skill_level',
                  'speech_type',]

actividades/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, reverse, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.generic import *
from django.utils.decorators import method_decorator
from django.utils.text import slugify
from actividades.forms import *
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.db import IntegrityError
from django.contrib.sites.shortcuts import get_current_site
from django.http import Http404
from django.core.exceptions import ObjectDoesNotExist
from django.http import JsonResponse, HttpResponseBadRequest


@method_decorator(login_required, name='dispatch')
class foro(ListView):
    template_name = 'foro/foro.html'

    def get(self, request, *arg, **kwargs):
        if get_current_site(request).domain == 'localhost:8000':
            raise Http404
        return super(foro, self).get(request, *arg, **kwargs)

    def get_queryset(self, *args, **kwargs):
        return Topic.objects.filter(sites=get_current_site(self.request)).order_by('-date_created')


@method_decorator(login_required, name='dispatch')
class foro_topic(ListView):

    template_name = 'foro/foro_topic.html'
    context_object_name = 'topic_list'

    def get_queryset(self, *args, **kwargs):
        self.editor = self.kwargs['slug']
        return Speech.objects.filter(topic__slug=self.editor, topic__sites=get_current_site(self.request)).order_by('-date_created')

    def get_context_data(self, **kwargs):
        context = super(foro_topic, self).get_context_data(**kwargs)
        try:
            context['topic'] = Topic.objects.get(slug=self.editor, sites=get_current_site(self.request))
        except ObjectDoesNotExist:
            raise Http404
        return context

    def get(self, request, *arg, **kwargs):
        if get_current_site(request).domain == 'localhost:8000':
            raise Http404
        return super(foro_topic, self).get(request, *arg, **kwargs)


@method_decorator(login_required, name='dispatch')
class foro_detail(ListView):

    template_name = 'foro/foro_detail.html'
    context_object_name = 'speech_details'

    def get_queryset(self, *args, **kwargs):
        self.editor = self.kwargs['slug']
        self.detalles = self.kwargs['slug1']
        return Speech.objects.get(topic__slug=self.editor, slug=self.detalles, topic__sites=get_current_site(self.request))

    def get(self, request, *arg, **kwargs):
        if get_current_site(request).domain == 'localhost:8000':
            raise Http404
        return super(foro_detail, self).get(request, *arg, **kwargs)


@method_decorator(login_required, name='dispatch')
class foro_types(ListView):

    template_name = 'foro/foro_types.html'
    context_object_name = 'foro_types'

    def get_queryset(self, *args, **kwargs):
        self.types = self.kwargs['slug']
        return Speech.objects.filter(speech_type__slug= self.types, topic__sites=get_current_site(self.request))

    def get(self, request, *arg, **kwargs):
        if get_current_site(request).domain == 'localhost:8000':
            raise Http404
        return super(foro_types, self).get(request, *arg, **kwargs)


@method_decorator(login_required, name='dispatch')
class insert_speech(SuccessMessageMixin, CreateView):
    template_name = 'foro/insert_speech.html'
    model = Speech
    form_class = InsertSpeech
    success_url = '/activity/'
    success_message = "La actividad fue creada. Necesita la aprobación de un administrador"

    def get(self, request, *arg, **kwargs):
        if get_current_site(request).domain == 'localhost:8000':
            raise Http404
        try:
            self.speech_slug = get_object_or_404(Speech, slug=self.kwargs['slug'])
        except Http404:
            self.topic_slug = get_object_or_404(Topic, slug=self.kwargs['slug'])
        return super(insert_speech, self).get(request, *arg, **kwargs)

    def form_valid(self, form):
        form.instance.user = self.request.user
        self.topic_slug = get_object_or_404(Topic, slug=self.kwargs['slug'])
        form.instance.topic = self.topic_slug
        form.instance.slug = slugify(form.instance.user.username + ' ' + form.instance.title)
        form.instance.sites = get_current_site(self.request)
        try:
            return super(insert_speech, self).form_valid(form)
        except IntegrityError:
            messages.add_message(self.request, messages.WARNING, 'Ya usted creo una actividad con el mismo título')
            return redirect('Insert_Speech', slug=self.kwargs['slug'])


@method_decorator(login_required, name='dispatch')
class subirRecurso(CreateView):
    model = SpeechResource
    fields = ('recurso', )
    template_name = 'foro/subir_recurso.html'

    def form_valid(self, form):
        form.instance.speech = get_object_or_404(Speech, pk=self.kwargs['speech_id'])
        form.instance.user = self.request.user
        form.instance.sites = get_current_site(self.request)
        return super(subirRecurso, self).form_valid(form)

    def get(self, request, *arg, **kwargs):
        if get_current_site(request).domain == 'localhost:8000':
            raise Http404
        return super(subirRecurso, self).get(request, *arg, **kwargs)


@method_decorator(login_required, name='dispatch')
class createProfile(SuccessMessageMixin, CreateView):
    template_name = 'usuarios_foro/create_profile.html'
    model = Forum_User_Profile
    form_class = EditProfileForm
    success_url = '/activity/'
    success_message = "La perfil fue creado con éxito"

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.sites = get_current_site(self.request)
        return super(createProfile, self).form_valid(form)


@method_decorator(login_required, name='dispatch')
class ProfileUpdateView(SuccessMessageMixin, UpdateView):
    form_class = EditProfileForm
    template_name = 'usuarios_foro/my_edit_profile.html'
    success_url = "/"
    model = Forum_User_Profile


@method_decorator(login_required, name='dispatch')
class view_profile_forum(DetailView):
    template_name = 'usuarios_foro/view_profile.html'
    model = Forum_User_Profile

    def get(self, request, *arg, **kwargs):
        if get_current_site(request).domain == 'localhost:8000':
            raise Http404
        return super(view_profile_forum, self).get(request, *arg, **kwargs)

actividades/templates/foro/foro.html
{% extends "sitios_web/base.html" %}
{% load i18n %}



{% block content %}
    {% if object_list %}
        <h1 class="page-header">
            {% trans "Temas" %}
        </h1>
    {% endif %}
    <div class="row foro">
        {% for  foo in object_list %}
            <div class="col-sm-4">
                <div class="card">
                    <div class="header">
                        <a href="{% url 'activity:Forum_Topic' foo.slug %}">
                            <h3>{{ foo.name }}</h3>
                        </a>
                    </div>
                    <div class="content">
                        <p>{{ foo.description|truncatewords:"30" }}</p>
                        <p class="date-activity"><span class="fa fa-calendar"></span>{{ foo.date_created }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
        {% if not object_list %}
            <div class="col-sm-12">
                <h3 class="text-warning">No existen aun temas que mostrar</h3>
                <br>
            </div>
        {% endif %}
    </div>
{% endblock %}

actividades/templates/foro/foro_detail.html
{% extends "sitios_web/base.html" %}
{% load i18n %}

{% block content %}

    <h1 class="page-header">{{ speech_details.title }}</h1>

    <div class="row-field">
        <strong class="row-item">Usuario:</strong>
        <p class="row-item">{{ speech_details.user.username }}</p>
    </div>
    <div class="clearfix"></div>
    <div class="row-field">
        <strong class="row-item">Detalles:</strong>
        <p class="row-item">{{ speech_details.description }}</p>
    </div>
    <div class="clearfix"></div>
    <div class="row-field">
        <strong class="row-item">Tipo de Actividad:</strong>
        <p class="row-item">{{ speech_details.speech_type.name }}</p>
    </div>
    <div class="clearfix"></div>
    <div class="row-field">
        <strong class="row-item">Acerca del autor:</strong>
        <p class="row-item">{{ speech_details.speaker_information }}</p>
    </div>
    <div class="clearfix"></div>
    <div class="row-field">
        <strong class="row-item">Para:</strong>
        <p class="row-item">{{ speech_details.audience }}</p>
    </div>
    <div class="clearfix"></div>
    <div class="row-field">
        <strong class="row-item">Nivel del Autor:</strong>
        <p class="row-item">{{ speech_details.skill_level }}</p>
    </div>


    {% if speech_details.user == user %}
        <br>
        <h2>Recursos</h2>
        {% for archivo in speech_details.recursos.all %}
            <div class="row-field">
                <strong class="row-item">Archivo:</strong>
                <p class="row-item">{{ archivo.nombre}}</p>
            <a href="#" onclick="eliminarRecurso({{archivo.pk}})">eliminar</a>
            </div>
            <br>
        {% empty %}
            <p>No existen recursos para esta actividad</p>
        {% endfor %}
        <br>
        <a href="{% url 'activity:subir_recurso' speech_details.pk %}" class="btn btn-success">Subir recurso</a>
   {% elif speech_details in user.profile.matriculatedspeechs.all %}
        <a class="matricula-link-detail" data-pk="{{ speech_details.pk}}">
            <span>Desmatricularme</span>
        </a>
   {% else %}
        <a class="matricula-link-detail" data-pk="{{ speech_details.pk}}">
            <span>Matricularme</span>
        </a>
    {% endif %}

{% endblock %}

{% block script %}

    <script type="text/javascript">
        $('.matricula-link-detail').click(function () {
            var id_speech = $(this).attr('data-pk');
            var element = $(this).find('span');
            matricular(element[0],id_speech);
        });

        function matricular(element, id_speech) {
            var texto = $(element).text();
            if (texto == 'Matricularme') {
                $(element).removeClass('animation-right');
                $(element).addClass('animation-left');
                $.ajax({
                    url: '/ajax/enroll/',
                    type: "POST",
                    data: {'id_speech': id_speech},
                    success: function (response) {
                        setTimeout(function () {
                            $(element).text(texto == 'Matricularme' ? 'Desmatricularme' : 'Matricularme');
                            $(element).addClass('animation-right');
                            $(element).removeClass('animation-left');
                        }, 1000);
                    }
                });
            } else {
                desmatricular(element, id_speech);
            }
        }
        function desmatricular(element, id_speech) {
            var texto = $(element).text();
            if (texto == 'Desmatricularme') {
                $(element).removeClass('animation-right');
                $(element).addClass('animation-left');
                $.ajax({
                    url: '/ajax/delete_enroll/',
                    type: "POST",
                    data: {'id_speech': id_speech},
                    success: function (response) {
                        setTimeout(function () {
                            var texto = $(element).text();
                            $(element).text(texto == 'Matricularme' ? 'Desmatricularme' : 'Matricularme');
                            $(element).addClass('animation-right');
                            $(element).removeClass('animation-left');
                        }, 1000);
                    }
                });
            }
            else {
                matricular(id_speech);
            }
        }
        function eliminarRecurso(id_recurso) {
            $.ajax({
                url: '/ajax/delete_recurso/',
                type: "POST",
                data: {'id_recurso': id_recurso},
                success: function (response) {
                    location.reload();
                }
            });
        }

    </script>

{% endblock %}

actividades/templates/foro/foro_topic.html
{% extends "sitios_web/base.html" %}
{% load i18n %}

{% load static %}

{% block content %}

    <h1 class="page-header">
        Actividades
        <a class="btn btn-primary pull-right" href="{% url 'activity:Insert_Speech' topic.slug %}">Insertar Actividad</a>
    </h1>

    <div class="row foro-topic">
        {% for foo in topic_list %}
            <div class="col-sm-3">
                <div class="card">
                    <div class="header">
                        <a href="{% url 'activity:Forum_Detail' foo.topic.slug foo.slug %}">
                            <h3>{{ foo.title }}</h3>
                        </a>
                    </div>
                    <div class="content">
                        <p>{{ foo.description|truncatewords:"30" }}</p>
                        <p class="date-activity"><span class="fa fa-user"></span>{{ foo.user.username }}</p>
                        <p><div class="likes activity-{{ foo.pk }}"><span>{{ foo.cantidad_de_likes }} Likes</span></div></p>

                        {% if foo.user == user %}
                        {% elif foo in user.profile.likes.all %}
                            <a class="icon-animation like-button" data-pk="{{ foo.pk }}">
                                <span class="fa icon-like  fa-thumbs-up"></span>
                            </a>
                        {% else %}
                            <a class="icon-animation like-button" data-pk="{{ foo.pk }}">
                                <span class="fa icon-like  fa-thumbs-o-up"></span>
                            </a>
                        {% endif %}

                        {% if foo.user == user %}
                        {% elif foo in user.profile.matriculatedspeechs.all %}
                            <a class="matricula-link" data-pk="{{ foo.pk }}">
                                <span>Desmatricularme</span>
                            </a>
                        {% else %}
                            <a class="matricula-link" data-pk="{{ foo.pk }}">
                                <span>Matricularme</span>
                            </a>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
        {% if not topic_list %}
            <div class="col-sm-12">
                <h3 class="text-warning">No hay actividades</h3>
            </div>
        {% endif %}
    </div>

{% endblock %}

{% block script %}
    <script type="text/javascript">
        var likes = 0;
        $('.like-button').click(function () {
            var id_speech = $(this).attr('data-pk');
            var element = $(this).find('.icon-like');
            if (!$(element[0]).hasClass('fa-thumbs-up')) {
                $(element[0]).addClass('animation-left');
                $.ajax({
                    url: '/ajax/add_like/',
                    type: "POST",
                    data: {'id_speech': id_speech},
                    success: function (response) {
                        console.log(response.messages);
                        likes = response.messages;
                        if(likes != 0) {
                            $('.activity-'+id_speech).find('span').remove();
                            $('.activity-'+id_speech).append('<span>'+ likes +'</span>');
                        }
                        setTimeout(function () {
                            $(element[0]).removeClass('fa-thumbs-o-up');
                            $(element[0]).addClass('fa-thumbs-up');
                            $(element[0]).addClass('animation-right');
                        }, 500);
                    }
                });
            }
        });


        $('.matricula-link').click(function () {
            var id_speech = $(this).attr('data-pk');
            var element = $(this).find('span');
            matricular(element[0],id_speech);
        });

        function matricular(element, id_speech) {
            var texto = $(element).text();
            if (texto == 'Matricularme') {
                $(element).removeClass('animation-right');
                $(element).addClass('animation-left');
                $.ajax({
                    url: '/ajax/enroll/',
                    type: "POST",
                    data: {'id_speech': id_speech},
                    success: function (response) {
                        setTimeout(function () {
                            $(element).text(texto == 'Matricularme' ? 'Desmatricularme' : 'Matricularme');
                            $(element).addClass('animation-right');
                            $(element).removeClass('animation-left');
                        }, 1000);
                    }
                });
            } else {
                desmatricular(element, id_speech);
            }
        }
        function desmatricular(element, id_speech) {
            var texto = $(element).text();
            if (texto == 'Desmatricularme') {
                $(element).removeClass('animation-right');
                $(element).addClass('animation-left');
                $.ajax({
                    url: '/ajax/delete_enroll/',
                    type: "POST",
                    data: {'id_speech': id_speech},
                    success: function (response) {
                        setTimeout(function () {
                            var texto = $(element).text();
                            $(element).text(texto == 'Matricularme' ? 'Desmatricularme' : 'Matricularme');
                            $(element).addClass('animation-right');
                            $(element).removeClass('animation-left');
                        }, 1000);
                    }
                });
            }
            else {
                matricular(id_speech);
            }
        }
    </script>
    <script src="{% static 'plataforma/js/same-height.js' %}"></script>
{% endblock %}

actividades/templates/foro/insert_speech.html
{% extends "sitios_web/base.html" %}
{% load i18n %}
{% load bootstrap3 %}
{% block content %}
    <h1>{% trans "New Speech" %}</h1>

    <div class="container">
        <form method="post">
            {% csrf_token %}
        {% bootstrap_field form.title %}
        {% bootstrap_field form.description %}
        {% bootstrap_field form.notes %}
        {% bootstrap_field form.speaker_information %}
        {% bootstrap_field form.audience %}
        {% bootstrap_field form.skill_level %}
        {% bootstrap_field form.speech_type %}

            <button class="btn btn-primary" type="submit">{% trans "Crear" %}</button>
        </form>
    </div>
{% endblock %}

actividades/templates/foro/insert_topic.html
{% extends "sitios_web/base.html" %}
{% load i18n %}
{% load bootstrap3 %}
{% block content %}
    <h1>{% trans "New Activity" %}</h1>

    <div class="container">
        <form method="post">
            {% csrf_token %}
        {% bootstrap_field form.name %}
        {% bootstrap_field form.description %}
            <button class="btn btn-primary" type="submit">{% trans "Crear" %}</button>
        </form>
    </div>
{% endblock %}

actividades/templates/foro/subir_recurso.html
{% extends "sitios_web/base.html" %}
{% load i18n %}
{% load bootstrap3 %}
{% block content %}
    <h1 class="page-header">{% trans "Nuevo recurso" %}</h1>

    <div class="container">
    <div class="row">
        <form method="post" class="col-sm-12" enctype="multipart/form-data">
            {% csrf_token %}
        {% bootstrap_form form %}
            <button class="btn btn-primary" type="submit">{% trans "Subir" %}</button>
        </form>
    </div>
    </div>
{% endblock %}